### ISSUE TITLE
Providing i18n strings

### ISSUE THREAD

**Issue by moniuch** [chillu/silverstripe-recaptcha#19]
Please provide an easy way to globally configure the `RecaptchaOptions.custom_translations` dictionary for languages not included by Google.

**Comment by chillu** [comment]
I'm not sure what this is referring to, there's no such option mentioned on https://developers.google.com/recaptcha/docs/display. There's `lang/en.yml` in the project, which you can use to provide translations (see `lang/fi.yml` for example)

**Comment by moniuch** [comment]
After 4 years and losing interest in silverstrip I will certainly not remember.
