### ISSUE TITLE
Upgrade Recaptcha to V2 - $150US bountysource

### ISSUE THREAD

**Issue by colinburns** [chillu/silverstripe-recaptcha#26]
I'm wondering if there are any plans to update this to V2 now that it has been released?

I started looking into the code to see if I could to see if I could upgrade the code, but I'm not too sure I follow the code very well.

**Comment by colinburns** [comment]
I recently discovered BountySource and given that I'd like someone else to do the work on this I thought I'd chuck on a bounty to get the work completed asap. If you're interested I've added a $150USD bounty to this issue.

https://www.bountysource.com/issues/23983531-upgrade-recaptcha-to-v2

**Comment by colinburns** [comment]
I've tested the code and this is all working fine for me edlinklater... I'm not sure if you have already received the bounty or if it doesn't get sent until this pull-request is merged in????

Thanks for the work on it...

**Comment by Firesphere** [comment]
Resolved in #36.

**Comment by bardiharborow** [comment]
@chillu I believe this issue should be closed, and the bounty allocated to @edlinklater and @Firesphere (maybe @colinburns needs to do that?).

**Comment by chillu** [comment]
Oh good stuff! I'll leave it to Colin to figure out how the bounty system applies here.

**Comment by colinburns** [comment]
@edlinklater & @Firesphere - sorry I assumed this would have been paid as Bountysource did take a credit card from me (I think but that was a long long time ago so not sure).

Please let me know as I'm happy to pay if it didn't get paid.

Cheers,
Colin

**Comment by Firesphere** [comment]
@colinburns I think you need to resolve it? Nothing got paid, that's for sure
