### ISSUE TITLE
Field is not showing up

### ISSUE THREAD

**Issue by iamrutvik** [chillu/silverstripe-recaptcha#35]
Hi,
I am using Recaptcha version 1 and spam protection v 0.4.

I have followed all steps mentioned on Readme and added a field called "Spam protector field". But the field is not showing up in the form on front end.

What I am doing wrong?

**Comment by Firesphere** [comment]
Hard to tell without seeing your code.
Just `RecaptchaField::create('spam');` should work.

**Comment by chillu** [comment]
No response, closing. I've verified that 2.0.2 of the module works with SilverStripe 3.x and spamprotection 2.0.8, both as a standalone field and with `enableSpamProtection()`.
