### ISSUE TITLE
User is verified, but captcha field validation fails on submission of form

### ISSUE THREAD

**Issue by cmcramer** [chillu/silverstripe-recaptcha#38]
ReCAPTCHA verifies the user, but every time form is submitted, the field fails and user is shown error next to captcha field telling them to answer captcha question. There are no additional errors in Apache log or Console.

**Comment by dasplan** [comment]
same here.
check RecaptchaField.php validate():
$request = Controller::curr()->getRequest();
i changed it to $request = Controller::curr()->getRequest()->postVars();
works for me.

**Comment by cmcramer** [comment]
Thanks. I submitted a pull request.

**Comment by frankmullenger** [comment]
This pull request addresses the same issue btw: https://github.com/chillu/silverstripe-recaptcha/pull/39

**Comment by Firesphere** [comment]
This has been addressed on the 2.0 branch and released as 2.0.1 today. Together with a few other minor fixes to make the code a bit more sane.
