### ISSUE TITLE
Bug using proxy

### ISSUE THREAD

**Issue by dio5** [chillu/silverstripe-recaptcha#41]
There's a bug in RecaptchaField_HTTPClient line 291-296 when using a proxy server.

Note how it's checking for the private RecaptchaField::$proxy_server.

**Comment by dio5** [comment]
Something like this should work:

$proxyServer = Config::inst()->get('RecaptchaField', 'proxy_server');
        if ($proxyServer) {
            curl_setopt($ch, CURLOPT_PROXY, $proxyServer);
            $proxyAuth = Config::inst()->get('RecaptchaField', 'proxy_auth');
            if ($proxyAuth) {
                curl_setopt($ch, CURLOPT_PROXYUSERPWD, $proxyAuth);
            }
        }

**Comment by chillu** [comment]
Thanks, fixed now!
