### ISSUE TITLE
PHP message: PHP Fatal error:  Cannot access private property RecaptchaField::$public_api_key in /container/application/public/mysite/_config.php on line 44

### ISSUE THREAD

**Issue by warm--tape** [chillu/silverstripe-recaptcha#44]
Getting above error after updating SS 3.4.1 to 3.6.0. Any ideas why Recaptcha is suddenly killing my site?

**Comment by chillu** [comment]
I'm not sure what your `mysite/_config.php` looks like, but if you follow the YAML based instructions from the README (on the 2.0 branch that's compatible with SilverStripe 3.x), you'll be fine.
